modLoader="javafml"
loaderVersion="[36,)"
license="Not specified"

[[mods]]
modId="boss_tools"
version="5.1"
displayName="Space-Bosstools"
credits="MrScautHD"
displayURL="https://www.curseforge.com/minecraft/mc-mods/space-bosstools"
authors="MrScautHD,PixKnight (Textures),Galacticraft (Mod idea)"
description='''
Fly to Other Planets!
'''

[[dependencies.boss_tools]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"


[[dependencies.boss_tools]]
    modId="obfuscate"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.boss_tools]]
    modId="obfuscate"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

